// THIS FILE IS AUTOGENERATED. DO NOT MODIFY DIRECTLY.

public protocol DependentType {
    associatedtype Value
    static var value: Value { get }
}

public extension Int {
    /// A type representing the the Int 0
    enum _0 : DependentType {
        public static var value: Int { 0 }
    }
    /// A type representing the the Int 1
    enum _1 : DependentType {
        public static var value: Int { 1 }
    }
    /// A type representing the the Int 2
    enum _2 : DependentType {
        public static var value: Int { 2 }
    }
    /// A type representing the the Int 3
    enum _3 : DependentType {
        public static var value: Int { 3 }
    }
    /// A type representing the the Int 4
    enum _4 : DependentType {
        public static var value: Int { 4 }
    }
    /// A type representing the the Int 5
    enum _5 : DependentType {
        public static var value: Int { 5 }
    }
    /// A type representing the the Int 6
    enum _6 : DependentType {
        public static var value: Int { 6 }
    }
    /// A type representing the the Int 7
    enum _7 : DependentType {
        public static var value: Int { 7 }
    }
    /// A type representing the the Int 8
    enum _8 : DependentType {
        public static var value: Int { 8 }
    }
    /// A type representing the the Int 9
    enum _9 : DependentType {
        public static var value: Int { 9 }
    }
    /// A type representing the the Int 10
    enum _10 : DependentType {
        public static var value: Int { 10 }
    }
}
public extension Double {
    /// A type representing the the Double 0
    enum _0 : DependentType {
        public static var value: Double { 0 }
    }
    /// A type representing the the Double 1
    enum _1 : DependentType {
        public static var value: Double { 1 }
    }
    /// A type representing the the Double 2
    enum _2 : DependentType {
        public static var value: Double { 2 }
    }
    /// A type representing the the Double 3
    enum _3 : DependentType {
        public static var value: Double { 3 }
    }
    /// A type representing the the Double 4
    enum _4 : DependentType {
        public static var value: Double { 4 }
    }
    /// A type representing the the Double 5
    enum _5 : DependentType {
        public static var value: Double { 5 }
    }
    /// A type representing the the Double 6
    enum _6 : DependentType {
        public static var value: Double { 6 }
    }
    /// A type representing the the Double 7
    enum _7 : DependentType {
        public static var value: Double { 7 }
    }
    /// A type representing the the Double 8
    enum _8 : DependentType {
        public static var value: Double { 8 }
    }
    /// A type representing the the Double 9
    enum _9 : DependentType {
        public static var value: Double { 9 }
    }
    /// A type representing the the Double 10
    enum _10 : DependentType {
        public static var value: Double { 10 }
    }
}

public extension String {
    enum Space : DependentType {
        public static let value: String = " "
    }
    
    enum NewLine : DependentType {
        public static let value: String = "\n"
    }
}

public extension Character {
    enum Space : DependentType {
        public static let value: Character = " "
    }
    
    enum NewLine : DependentType {
        public static let value: Character = "\n"
    }
}

public extension Bool {
    enum True : DependentType {
        public static let value: Bool = true
    }
    
    enum False : DependentType {
        public static let value: Bool = false
    }
}
